numJIMWLK++: momenta Class Reference
momenta Class Reference
#include <momenta.h>
Public Member Functions
momenta (config *cnfg, mpi_class *mpi)
~momenta ()
int set ()
double phat2 (int i)
double pbarX (int i)
double pbarY (int i)
Private Attributes
double * tbl_phat2 = NULL
double * tbl_phatx = NULL
double * tbl_phaty = NULL
double * tbl_pbar2 = NULL
double * tbl_pbarx = NULL
double * tbl_pbary = NULL
int Nxl
int Nyl
int pos_x
int pos_y
Detailed Description
Definition at line 39 of file momenta.h.
Constructor & Destructor Documentation
momenta()
momenta::momenta (config * cnfg, mpi_class * mpi) inline
Definition at line 55 of file momenta.h.
References mpi_class::getPosX(), mpi_class::getPosY(), config::Nxl, and config::Nyl.
~momenta()
momenta::~momenta () inline
Definition at line 97 of file momenta.h.
References pbarX(), pbarY(), and phat2().
Member Function Documentation
pbarX()
double momenta::pbarX (int i)
Definition at line 158 of file momenta.h.
References tbl_pbarx.
Referenced by prepare_A_local(), lfield< T, t >::setKernelPbarX(), lfield< T, t >::setKernelPbarXWithCouplingConstant(), and ~momenta().
pbarY()
double momenta::pbarY (int i)
Definition at line 163 of file momenta.h.
References tbl_pbary.
Referenced by prepare_A_local(), lfield< T, t >::setKernelPbarY(), lfield< T, t >::setKernelPbarYWithCouplingConstant(), and ~momenta().
phat2()
double momenta::phat2 (int i)
Definition at line 153 of file momenta.h.
References tbl_phat2.
Referenced by generate_gaussian_with_noise_coupling_constant(), main(), prepare_A_local(), lfield< T, t >::print(), print(), lfield< T, t >::setCorrelationsForCouplingConstant(), lfield< T, t >::setKernelPbarX(), lfield< T, t >::setKernelPbarXWithCouplingConstant(), lfield< T, t >::setKernelPbarY(), lfield< T, t >::setKernelPbarYWithCouplingConstant(), lfield< T, t >::solvePoisson(), and ~momenta().
set()
int momenta::set ()
Definition at line 116 of file momenta.h.
References Nx, Nxl, Ny, Nyl, pos_x, pos_y, tbl_pbar2, tbl_pbarx, tbl_pbary, tbl_phat2, tbl_phatx, and tbl_phaty.
Referenced by main().
Member Data Documentation
Nxl
int momenta::Nxl private
Definition at line 50 of file momenta.h.
Referenced by set().
Nyl
int momenta::Nyl private
Definition at line 50 of file momenta.h.
Referenced by set().
pos_x
int momenta::pos_x private
Definition at line 51 of file momenta.h.
Referenced by set().
pos_y
int momenta::pos_y private
Definition at line 51 of file momenta.h.
Referenced by set().
tbl_pbar2
double* momenta::tbl_pbar2 = NULL private
Definition at line 46 of file momenta.h.
Referenced by set().
tbl_pbarx
double* momenta::tbl_pbarx = NULL private
Definition at line 47 of file momenta.h.
Referenced by pbarX(), and set().
tbl_pbary
double* momenta::tbl_pbary = NULL private
Definition at line 48 of file momenta.h.
Referenced by pbarY(), and set().
tbl_phat2
double* momenta::tbl_phat2 = NULL private
Definition at line 43 of file momenta.h.
Referenced by phat2(), and set().
tbl_phatx
double* momenta::tbl_phatx = NULL private
Definition at line 44 of file momenta.h.
Referenced by set().
tbl_phaty
double* momenta::tbl_phaty = NULL private
Definition at line 45 of file momenta.h.
Referenced by set().
The documentation for this class was generated from the following file:
momenta.h