numJIMWLK++: lfield< T, t > Class Template Reference
lfield< T, t > Class Template Reference
#include <field.h>
Public Member Functions
lfield (int NNx, int NNy)
lfield (const lfield< T, t > &in)
~lfield ()
int mpi_exchange_boundaries (mpi_class *mpi)
Function exchanging boundary values through MPI Send and Recv functions.
int getNxl (void) const
int getNyl (void) const
int loc_pos (int x, int y)
int buf_pos (int x, int y)
int buf_pos_ex (int x, int y)
int setToZero (void)
int setToUnit (void)
int setToOne (void)
int setToFixed (void)
int setMVModel (MV_class *MVconfig)
Method to set the values of lfield object according to the McLerran-Venugopalan model.
int setUnitModel (rand_class *rr)
Method to set the values of lfield object with gaussian distribution for all matrix elements.
int setGaussian (void)
Method to set the values of lfield object with gaussian distribution in the SU(3) group.
int solvePoisson (double mass, double g, momenta *momtable)
Implements the solution of the Poisson equation in momentum space, Eq.
int exponentiate ()
Function to exponentiate elements of the Lie algebra to obtain Lie group elements.
int exponentiate (double s)
Function to exponentiate elements of the Lie algebra to obtain Lie group elements.
int setKernelPbarX (momenta *mom, mpi_class *mpi, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in momentum space, the x component.
int setKernelPbarY (momenta *mom, mpi_class *mpi, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in momentum space, the y component.
int setKernelPbarXWithCouplingConstant (momenta *mom, mpi_class *mpi, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in momentum space, the x component.
int setKernelPbarYWithCouplingConstant (momenta *mom, mpi_class *mpi, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in momentum space, the y component.
int setCorrelationsForCouplingConstant (momenta *mom)
The method creates a one-element lfield object with the value of the coupling constant evaluated for each distance.
lfield< T, t > * hermitian ()
Returns a lfield with the matrices on all sites hermitian conjugated.
lfield< T, t > & operator= (const lfield< T, t > &f)
lfield< T, t > & operator*= (const lfield< T, t > &f)
Overloaded multiplication and assignement operator.
lfield< T, t > & operator+= (const lfield< T, t > &f)
int trace (lfield< double, 1 > *cc)
For all sites of the local lfield, the method computes the trace and stores it in the one element lfield object provided by the pointer in the argument.
int average (lfield< double, 1 > *cc)
For all sites of the local lfield, the method takes the first element and stores it in the one element lfield object provided by the pointer in the argument.
int reduceAndSet (int x, int y, gfield< T, t > *field)
The method reduces the global gfield object into local lfield by performing a sum over the volume.
int print (momenta *mom)
Simple print function.
int print (momenta *mom, double x, mpi_class *mpi)
Simple print function.
int printDebug ()
Simple print function.
int printDebug (double x)
Simple print function.
int printDebug (int i)
Simple print function.
int printDebug (double x, mpi_class *mpi)
Simple print function.
int printDebugRadial (double x)
Simple print function.
Public Member Functions inherited from field< T, t >
field (int NNx, int NNy)
Constructor.
field (const field< T, t > &in)
Copy constructor.
virtual ~field (void)
Public Attributes
Nyl = NNy
Public Attributes inherited from field< T, t >
std::complex< T > * u
Private Attributes
int Nxl
int Nyl
int Nxl_buf
int Nyl_buf
Friends
class fftw2D
class gfield< T, t >
Detailed Description
template<class T, int t>
class lfield< T, t >
Definition at line 120 of file field.h.
Constructor & Destructor Documentation
lfield() [1/2]
template<class T, int t> lfield< T, t >::lfield (int NNx, int NNy) inline
Definition at line 202 of file field.h.
lfield() [2/2]
template<class T , int t> lfield< T, t >::lfield (const lfield< T, t > & in)
Definition at line 336 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), lfield< T, t >::Nxl, and lfield< T, t >::Nyl.
~lfield()
template<class T , int t> lfield< T, t >::~lfield ()
Definition at line 346 of file field.h.
References field< T, t >::u.
Member Function Documentation
average()
template<class T , int t> int lfield< T, t >::average (lfield< double, 1 > * cc)
For all sites of the local lfield, the method takes the first element and stores it in the one element lfield object provided by the pointer in the argument.
For testing purposes only, not used in physical application.
Definition at line 1684 of file field.h.
References lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
buf_pos()
template<class T, int t> int lfield< T, t >::buf_pos (int x, int y) inline
Definition at line 226 of file field.h.
Referenced by lfield< T, t >::mpi_exchange_boundaries().
buf_pos_ex()
template<class T, int t> int lfield< T, t >::buf_pos_ex (int x, int y) inline
Definition at line 231 of file field.h.
Referenced by lfield< T, t >::mpi_exchange_boundaries().
exponentiate() [1/2]
template<class T , int t> int lfield< T, t >::exponentiate ()
Function to exponentiate elements of the Lie algebra to obtain Lie group elements.
Note that for the initial condition the optimized version uses the exponentiation in the overloaded *= operator.
The argument allows to include a - sign before exponentiation, without an additional loop
Definition at line 981 of file field.h.
References su3_matrix< T >::exponentiate(), su3_matrix< T >::m, lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
Referenced by main().
exponentiate() [2/2]
template<class T , int t> int lfield< T, t >::exponentiate (double s)
Function to exponentiate elements of the Lie algebra to obtain Lie group elements.
Note that for the initial condition the optimized version uses the exponentiation in the overloaded *= operator. Additional scaling for the Langevin step size is passed as the double argument.
The argument allows to include a - sign before exponentiation, without an additional loop
Definition at line 1009 of file field.h.
References su3_matrix< T >::exponentiate(), su3_matrix< T >::m, lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
getNxl()
template<class T, int t> int lfield< T, t >::getNxl (void) const inline
Definition at line 213 of file field.h.
References field< T, t >::Nxl.
Referenced by gfield< T, t >::allgather(), generate_gaussian(), generate_gaussian_with_noise_coupling_constant(), lfield< T, t >::lfield(), operator*(), lfield< T, t >::operator*=(), operator+(), lfield< T, t >::operator+=(), lfield< T, t >::operator=(), prepare_A_local(), print(), gfield< T, t >::reduce(), gfield< T, t >::reduce_hatta(), update_uf(), and uxiulocal().
getNyl()
template<class T, int t> int lfield< T, t >::getNyl (void) const inline
Definition at line 217 of file field.h.
References field< T, t >::Nyl.
Referenced by gfield< T, t >::allgather(), generate_gaussian(), generate_gaussian_with_noise_coupling_constant(), lfield< T, t >::lfield(), operator*(), lfield< T, t >::operator*=(), operator+(), lfield< T, t >::operator+=(), lfield< T, t >::operator=(), prepare_A_and_B_local(), prepare_A_local(), print(), gfield< T, t >::reduce(), gfield< T, t >::reduce_hatta(), update_uf(), and uxiulocal().
hermitian()
template<class T , int t> lfield< T, t > * lfield< T, t >::hermitian (void)
Returns a lfield with the matrices on all sites hermitian conjugated.
In the optimized version this operation is merged with other steps.
Definition at line 1563 of file field.h.
References lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
Referenced by main().
loc_pos()
template<class T, int t> int lfield< T, t >::loc_pos (int x, int y) inline
Definition at line 221 of file field.h.
mpi_exchange_boundaries()
template<class T > int lfield< T >::mpi_exchange_boundaries (mpi_class * mpi)
Function exchanging boundary values through MPI Send and Recv functions.
Not used at the moment. May be useful for the parallel calculation of correlation functions with Wilson line derivatives.
Definition at line 663 of file field.h.
References lfield< T, t >::buf_pos(), lfield< T, t >::buf_pos_ex(), mpi_class::getExchangeX(), mpi_class::getRank(), mpi_class::getXNeighbourNext(), mpi_class::getXNeighbourPrevious(), lfield< T, t >::Nxl, lfield< T, t >::Nyl, lfield< T, t >::Nyl_buf, and field< T, t >::u.
operator*=()
template<class T , int t> lfield< T, t > & lfield< T, t >::operator*= (const lfield< T, t > & f)
Overloaded multiplication and assignement operator.
In the optimized version the exponentiation from the Lie algebra to the Lie group is included in order to minimize thread creation and synchronization.
Definition at line 392 of file field.h.
References su3_matrix< T >::exponentiate(), lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), su3_matrix< T >::m, and field< T, t >::u.
operator+=()
template<class T , int t> lfield< T, t > & lfield< T, t >::operator+= (const lfield< T, t > & f)
Definition at line 422 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), and field< T, t >::u.
operator=()
template<class T , int t> lfield< T, t > & lfield< T, t >::operator= (const lfield< T, t > & f)
Definition at line 352 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), and field< T, t >::u.
print() [1/2]
template<class T , int t> int lfield< T, t >::print (momenta * mom)
Simple print function.
Not used in the optimized version.
Definition at line 1890 of file field.h.
References lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
print() [2/2]
template<class T , int t> int lfield< T, t >::print (momenta * mom, double x, mpi_class * mpi)
Simple print function.
Not used in the optimized version.
Definition at line 1911 of file field.h.
References mpi_class::getPosX(), mpi_class::getPosY(), mpi_class::getRank(), mpi_class::getSize(), lfield< T, t >::Nxl, lfield< T, t >::Nyl, momenta::phat2(), and field< T, t >::u.
printDebug() [1/4]
template<class T , int t> int lfield< T, t >::printDebug (void)
Simple print function.
Not used in the optimized version.
Definition at line 1983 of file field.h.
References lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
Referenced by main().
printDebug() [2/4]
template<class T , int t> int lfield< T, t >::printDebug (double x)
Simple print function.
Not used in the optimized version.
Definition at line 2023 of file field.h.
References lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
printDebug() [3/4]
template<class T , int t> int lfield< T, t >::printDebug (int ii)
Simple print function.
Not used in the optimized version.
Definition at line 2048 of file field.h.
References lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
printDebug() [4/4]
template<class T , int t> int lfield< T, t >::printDebug (double x, mpi_class * mpi)
Simple print function.
Not used in the optimized version.
Definition at line 2078 of file field.h.
References mpi_class::getPosX(), mpi_class::getPosY(), lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
printDebugRadial()
template<class T , int t> int lfield< T, t >::printDebugRadial (double x)
Simple print function.
Not used in the optimized version.
Definition at line 2095 of file field.h.
References lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
reduceAndSet()
template<class T , int t> int lfield< T, t >::reduceAndSet (int x_local, int y_local, gfield< T, t > * f)
The method reduces the global gfield object into local lfield by performing a sum over the volume.
Used in the explicit formulation.
Definition at line 1801 of file field.h.
References gfield< T, t >::getNxg(), gfield< T, t >::getNyg(), lfield< T, t >::Nyl, and field< T, t >::u.
Referenced by main().
setCorrelationsForCouplingConstant()
template<class T , int t> int lfield< T, t >::setCorrelationsForCouplingConstant (momenta * mom)
The method creates a one-element lfield object with the value of the coupling constant evaluated for each distance.
Definition at line 1829 of file field.h.
References Nx, lfield< T, t >::Nxl, Ny, lfield< T, t >::Nyl, momenta::phat2(), and field< T, t >::u.
Referenced by main().
setGaussian()
template<class T , int t> int lfield< T, t >::setGaussian (void)
Method to set the values of lfield object with gaussian distribution in the SU(3) group.
Thread parallelized. Not used in physical application.
Definition at line 890 of file field.h.
References lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
Referenced by main().
setKernelPbarX()
template<class T , int t> int lfield< T, t >::setKernelPbarX (momenta * mom, mpi_class * mpi, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in momentum space, the x component.
Takes for arguments the momenta object for global momenta values, the mpi_class for parallelization, and the KernelChoice. In the optimized implementation this is included in the prepare_A_local function.
Definition at line 1037 of file field.h.
References mpi_class::getPosX(), mpi_class::getPosY(), LINEAR_KERNEL, Nx, lfield< T, t >::Nxl, Ny, lfield< T, t >::Nyl, momenta::pbarX(), momenta::phat2(), SIN_KERNEL, and field< T, t >::u.
Referenced by main().
setKernelPbarXWithCouplingConstant()
template<class T , int t> int lfield< T, t >::setKernelPbarXWithCouplingConstant (momenta * mom, mpi_class * mpi, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in momentum space, the x component.
Takes for arguments the momenta object for global momenta values, the mpi_class for parallelization, and the KernelChoice. It includes the running coupling. In the optimized version this is included in the prepare_A_local function.
Definition at line 1149 of file field.h.
References mpi_class::getPosX(), mpi_class::getPosY(), LINEAR_KERNEL, Nx, lfield< T, t >::Nxl, Ny, lfield< T, t >::Nyl, momenta::pbarX(), momenta::phat2(), SIN_KERNEL, and field< T, t >::u.
Referenced by main().
setKernelPbarY()
template<class T , int t> int lfield< T, t >::setKernelPbarY (momenta * mom, mpi_class * mpi, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in momentum space, the y component.
Takes for arguments the momenta object for global momenta values, the mpi_class for parallelization, and the KernelChoice. In the optimized version this is included in the prepare_A_local function.
Definition at line 1092 of file field.h.
References mpi_class::getPosX(), mpi_class::getPosY(), LINEAR_KERNEL, Nx, lfield< T, t >::Nxl, Ny, lfield< T, t >::Nyl, momenta::pbarY(), momenta::phat2(), SIN_KERNEL, and field< T, t >::u.
Referenced by main().
setKernelPbarYWithCouplingConstant()
template<class T , int t> int lfield< T, t >::setKernelPbarYWithCouplingConstant (momenta * mom, mpi_class * mpi, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in momentum space, the y component.
Takes for arguments the momenta object for global momenta values, the mpi_class for parallelization, and the KernelChoice. It includes the running coupling. In the optimized version this is included in the prepare_A_local function.
Definition at line 1205 of file field.h.
References mpi_class::getPosX(), mpi_class::getPosY(), LINEAR_KERNEL, Nx, lfield< T, t >::Nxl, Ny, lfield< T, t >::Nyl, momenta::pbarY(), momenta::phat2(), SIN_KERNEL, and field< T, t >::u.
Referenced by main().
setMVModel()
template<class T , int t> int lfield< T, t >::setMVModel (MV_class * MVconfig)
Method to set the values of lfield object according to the McLerran-Venugopalan model.
Model parameters are transferred though the MV_class object.
Definition at line 776 of file field.h.
References MV_class::gGet(), MV_class::muGet(), lfield< T, t >::Nxl, MV_class::NyGet(), lfield< T, t >::Nyl, and field< T, t >::u.
Referenced by main().
setToFixed()
template<class T, int t> int lfield< T, t >::setToFixed (void) inline
Definition at line 271 of file field.h.
References gfield< T, t >::hermitian(), field< T, t >::Nxl, field< T, t >::Nyl, gfield< T, t >::operator=(), print(), gfield< T, t >::printDebug(), gfield< T, t >::setCorrelationsForCouplingConstant(), and field< T, t >::u.
Referenced by main().
setToOne()
template<class T, int t> int lfield< T, t >::setToOne (void) inline
Definition at line 263 of file field.h.
References field< T, t >::Nyl, and field< T, t >::u.
Referenced by main().
setToUnit()
template<class T, int t> int lfield< T, t >::setToUnit (void) inline
Definition at line 247 of file field.h.
References field< T, t >::Nyl, and field< T, t >::u.
Referenced by main().
setToZero()
template<class T, int t> int lfield< T, t >::setToZero (void) inline
Definition at line 237 of file field.h.
References field< T, t >::Nyl, and field< T, t >::u.
Referenced by main(), operator*(), and operator+().
setUnitModel()
template<class T , int t> int lfield< T, t >::setUnitModel (rand_class * rr)
Method to set the values of lfield object with gaussian distribution for all matrix elements.
Receives a pointer to the wrapper of the C++ random generator. Not parallelized with threads. Not used in physical application.
Definition at line 855 of file field.h.
References rand_class::get(), lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
solvePoisson()
template<class T , int t> int lfield< T, t >::solvePoisson (double mass, double g, momenta * mom)
Implements the solution of the Poisson equation in momentum space, Eq.
4 of arxiv XXXXXX
Definition at line 966 of file field.h.
References lfield< T, t >::Nxl, lfield< T, t >::Nyl, momenta::phat2(), and field< T, t >::u.
Referenced by main().
trace()
template<class T , int t> int lfield< T, t >::trace (lfield< double, 1 > * cc)
For all sites of the local lfield, the method computes the trace and stores it in the one element lfield object provided by the pointer in the argument.
Definition at line 1637 of file field.h.
References su3_matrix< T >::m, lfield< T, t >::Nxl, lfield< T, t >::Nyl, and field< T, t >::u.
Referenced by main().
Friends And Related Function Documentation
fftw2D
template<class T, int t> friend class fftw2D friend
Definition at line 207 of file field.h.
gfield< T, t >
template<class T, int t> friend class gfield< T, t > friend
Definition at line 211 of file field.h.
Member Data Documentation
Nxl
template<class T, int t> int lfield< T, t >::Nxl private
Definition at line 197 of file field.h.
Referenced by gfield< T, t >::allgather(), lfield< T, t >::average(), lfield< T, t >::exponentiate(), lfield< T, t >::hermitian(), lfield< T, t >::lfield(), lfield< T, t >::mpi_exchange_boundaries(), lfield< T, t >::print(), lfield< T, t >::printDebug(), lfield< T, t >::printDebugRadial(), lfield< T, t >::setCorrelationsForCouplingConstant(), lfield< T, t >::setGaussian(), lfield< T, t >::setKernelPbarX(), lfield< T, t >::setKernelPbarXWithCouplingConstant(), lfield< T, t >::setKernelPbarY(), lfield< T, t >::setKernelPbarYWithCouplingConstant(), lfield< T, t >::setMVModel(), lfield< T, t >::setUnitModel(), lfield< T, t >::solvePoisson(), and lfield< T, t >::trace().
Nxl_buf
template<class T, int t> int lfield< T, t >::Nxl_buf private
Definition at line 198 of file field.h.
Nyl [1/2]
template<class T, int t> int lfield< T, t >::Nyl private
Definition at line 197 of file field.h.
Referenced by lfield< T, t >::average(), lfield< T, t >::exponentiate(), lfield< T, t >::hermitian(), lfield< T, t >::lfield(), lfield< T, t >::mpi_exchange_boundaries(), lfield< T, t >::print(), lfield< T, t >::printDebug(), lfield< T, t >::printDebugRadial(), lfield< T, t >::reduceAndSet(), lfield< T, t >::setCorrelationsForCouplingConstant(), lfield< T, t >::setGaussian(), lfield< T, t >::setKernelPbarX(), lfield< T, t >::setKernelPbarXWithCouplingConstant(), lfield< T, t >::setKernelPbarY(), lfield< T, t >::setKernelPbarYWithCouplingConstant(), lfield< T, t >::setMVModel(), lfield< T, t >::setUnitModel(), lfield< T, t >::solvePoisson(), and lfield< T, t >::trace().
Nyl [2/2]
template<class T, int t> lfield< T, t >::Nyl = NNy
Definition at line 202 of file field.h.
Nyl_buf
template<class T, int t> int lfield< T, t >::Nyl_buf private
Definition at line 198 of file field.h.
Referenced by lfield< T, t >::mpi_exchange_boundaries().
The documentation for this class was generated from the following files:
field.h
mpi_exchange_boundaries.cpp