numJIMWLK++: positions Class Reference
positions Class Reference
#include <positions.h>
Public Member Functions
positions (config *cnfg, mpi_class *mpi)
positions (const positions &in)
~positions ()
int set ()
double xhatX (int i)
double xhatY (int i)
double xbar2 (int i)
Private Attributes
double * tbl_xhatx = NULL
double * tbl_xhaty = NULL
double * tbl_xbar2 = NULL
int Nxg
int Nyg
int pos_x
int pos_y
Detailed Description
Definition at line 38 of file positions.h.
Constructor & Destructor Documentation
positions() [1/2]
positions::positions (config * cnfg, mpi_class * mpi) inline
Definition at line 51 of file positions.h.
References mpi_class::getPosX(), mpi_class::getPosY(), Nx, and Ny.
positions() [2/2]
positions::positions (const positions & in) inline
Definition at line 79 of file positions.h.
References Nxg, Nyg, pos_x, pos_y, tbl_xbar2, tbl_xhatx, and tbl_xhaty.
~positions()
positions::~positions () inline
Definition at line 103 of file positions.h.
References xbar2(), xhatX(), and xhatY().
Member Function Documentation
set()
int positions::set ()
Definition at line 119 of file positions.h.
References Nx, Ny, tbl_xbar2, tbl_xhatx, and tbl_xhaty.
Referenced by main().
xbar2()
double positions::xbar2 (int i)
Definition at line 181 of file positions.h.
References tbl_xbar2.
Referenced by prepare_A_and_B_local(), gfield< T, t >::setKernelXbarX(), gfield< T, t >::setKernelXbarXWithCouplingConstant(), gfield< T, t >::setKernelXbarY(), gfield< T, t >::setKernelXbarYWithCouplingConstant(), and ~positions().
xhatX()
double positions::xhatX (int i)
Definition at line 186 of file positions.h.
References tbl_xhatx.
Referenced by prepare_A_and_B_local(), gfield< T, t >::setKernelXbarX(), gfield< T, t >::setKernelXbarXWithCouplingConstant(), gfield< T, t >::setKernelXbarY(), gfield< T, t >::setKernelXbarYWithCouplingConstant(), and ~positions().
xhatY()
double positions::xhatY (int i)
Definition at line 191 of file positions.h.
References tbl_xhaty.
Referenced by prepare_A_and_B_local(), gfield< T, t >::setKernelXbarX(), gfield< T, t >::setKernelXbarXWithCouplingConstant(), gfield< T, t >::setKernelXbarY(), gfield< T, t >::setKernelXbarYWithCouplingConstant(), and ~positions().
Member Data Documentation
Nxg
int positions::Nxg private
Definition at line 46 of file positions.h.
Referenced by positions().
Nyg
int positions::Nyg private
Definition at line 46 of file positions.h.
Referenced by positions().
pos_x
int positions::pos_x private
Definition at line 47 of file positions.h.
Referenced by positions().
pos_y
int positions::pos_y private
Definition at line 47 of file positions.h.
Referenced by positions().
tbl_xbar2
double* positions::tbl_xbar2 = NULL private
Definition at line 44 of file positions.h.
Referenced by positions(), set(), and xbar2().
tbl_xhatx
double* positions::tbl_xhatx = NULL private
Definition at line 42 of file positions.h.
Referenced by positions(), set(), and xhatX().
tbl_xhaty
double* positions::tbl_xhaty = NULL private
Definition at line 43 of file positions.h.
Referenced by positions(), set(), and xhatY().
The documentation for this class was generated from the following file:
positions.h