numJIMWLK++: gfield< T, t > Class Template Reference
gfield< T, t > Class Template Reference
Derived class gfield.
#include <field.h>
Public Member Functions
int allgather (lfield< T, t > *ulocal, mpi_class *mpi)
Specialization of the MPI Allgather function to the lfield class.
gfield (int NNx, int NNy)
~gfield ()
Derived class destructor.
int getNxg (void) const
int getNyg (void) const
int average_and_symmetrize ()
The method symmetrizes the data assuming x <-> y symmetry (rotations by 90 degrees) and mirror images along the Nx/2 and Ny/2 axes.
gfield< T, t > & operator= (const gfield< T, t > &f)
gfield< T, t > * hermitian ()
Returns a gfield with the matrices on all sites hermitian conjugated.
int setKernelXbarX (int x, int y, positions *postable, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in position space, the x component.
int setKernelXbarY (int x, int y, positions *postable, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in position space, the y component.
int setKernelXbarXWithCouplingConstant (int x, int y, positions *postable, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in position space, the x component.
int setKernelXbarYWithCouplingConstant (int x, int y, positions *postable, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in position space, the x component.
int setCorrelationsForCouplingConstant ()
int multiplyByCholesky (gmatrix< T > *mm)
The method multiplies the global gfield object by the Cholesky decomposition of the correation matrix.
int reduce (lfield< T, t > *sum, lfield< T, t > *err, mpi_class *mpi)
The method reduces the global gfield object into local lfield sum and lfield err objects: each MPI rank takes the appropriate part of the global object.
int reduce_hatta (lfield< T, t > *sum, lfield< T, t > *err, mpi_class *mpi, int xr, int yr)
The method reduces the global gfield object into local lfield sum and lfield err objects: each MPI rank takes the appropriate part of the global object.
int setToZero (void)
int printDebug (void)
Simple print function.
Public Member Functions inherited from field< T, t >
field (int NNx, int NNy)
Constructor.
field (const field< T, t > &in)
Copy constructor.
virtual ~field (void)
Public Attributes
Nyg = NNy
Public Attributes inherited from field< T, t >
std::complex< T > * u
Private Attributes
int Nxg
Specialization of the field class to a GLOBAL object.
int Nyg
Friends
class fftw2D
Detailed Description
template<class T, int t>
class gfield< T, t >
Derived class gfield.
Contains the entire object on each node. Nxg and Nyg refer to the total size of the lattice.
Definition at line 127 of file field.h.
Constructor & Destructor Documentation
gfield()
template<class T, int t> gfield< T, t >::gfield (int NNx, int NNy) inline
Definition at line 141 of file field.h.
Referenced by gfield< T, t >::average_and_symmetrize().
~gfield()
template<class T , int t> gfield< T, t >::~gfield ()
Derived class destructor.
Definition at line 187 of file field.h.
References field< T, t >::u.
Member Function Documentation
allgather()
template<class T , int t> int gfield< T, t >::allgather (lfield< T, t > * ulocal, mpi_class * mpi)
Specialization of the MPI Allgather function to the lfield class.
Takes data from local lfield objects and copies it to gfield class. Works only with parallelization in a single direction: x-direction is assumed to be parallelized.
Definition at line 592 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), mpi_class::getSize(), gfield< T, t >::Nxg, lfield< T, t >::Nxl, gfield< T, t >::Nyg, and field< T, t >::u.
Referenced by main().
average_and_symmetrize()
template<class T , int t> int gfield< T, t >::average_and_symmetrize (void)
The method symmetrizes the data assuming x <-> y symmetry (rotations by 90 degrees) and mirror images along the Nx/2 and Ny/2 axes.
Definition at line 1711 of file field.h.
References gfield< T, t >::gfield(), Nx, Ny, and field< T, t >::u.
getNxg()
template<class T, int t> int gfield< T, t >::getNxg (void) const inline
Definition at line 147 of file field.h.
Referenced by operator*(), operator+(), gfield< T, t >::operator=(), and lfield< T, t >::reduceAndSet().
getNyg()
template<class T, int t> int gfield< T, t >::getNyg (void) const inline
Definition at line 151 of file field.h.
Referenced by operator*(), operator+(), gfield< T, t >::operator=(), and lfield< T, t >::reduceAndSet().
hermitian()
template<class T , int t> gfield< T, t > * gfield< T, t >::hermitian (void)
Returns a gfield with the matrices on all sites hermitian conjugated.
Not used.
Definition at line 1600 of file field.h.
References Nx, Ny, and field< T, t >::u.
Referenced by main(), and lfield< T, t >::setToFixed().
multiplyByCholesky()
template<class T , int t> int gfield< T, t >::multiplyByCholesky (gmatrix< T > * mm)
The method multiplies the global gfield object by the Cholesky decomposition of the correation matrix.
Definition at line 1852 of file field.h.
References gfield< T, t >::Nxg, gfield< T, t >::Nyg, matrix< T >::u, and field< T, t >::u.
Referenced by main().
operator=()
template<class T , int t> gfield< T, t > & gfield< T, t >::operator= (const gfield< T, t > & f)
Definition at line 371 of file field.h.
References gfield< T, t >::getNxg(), gfield< T, t >::getNyg(), and field< T, t >::u.
Referenced by lfield< T, t >::setToFixed().
printDebug()
template<class T , int t> int gfield< T, t >::printDebug (void)
Simple print function.
Not used in the optimized version.
Definition at line 2003 of file field.h.
References gfield< T, t >::Nxg, gfield< T, t >::Nyg, and field< T, t >::u.
Referenced by lfield< T, t >::setToFixed().
reduce()
template<class T , int t> int gfield< T, t >::reduce (lfield< T, t > * sum, lfield< T, t > * err, mpi_class * mpi)
The method reduces the global gfield object into local lfield sum and lfield err objects: each MPI rank takes the appropriate part of the global object.
Definition at line 1748 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), mpi_class::getPosX(), mpi_class::getPosY(), Ny, and field< T, t >::u.
reduce_hatta()
template<class T , int t> int gfield< T, t >::reduce_hatta (lfield< T, t > * sum, lfield< T, t > * err, mpi_class * mpi, int xr, int yr)
The method reduces the global gfield object into local lfield sum and lfield err objects: each MPI rank takes the appropriate part of the global object.
Specialization to the HATTA_COUPLING_CONSTANT: we take from the global object only the elements for which the correlation function was evaluated, given by the two integer arguments xr and yr.
!! we should only select the momenta which correspond to the distance rr !!!
Definition at line 1767 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), mpi_class::getPosX(), mpi_class::getPosY(), Ny, and field< T, t >::u.
setCorrelationsForCouplingConstant()
template<class T, int t> int gfield< T, t >::setCorrelationsForCouplingConstant ()
Referenced by lfield< T, t >::setToFixed().
setKernelXbarX()
template<class T , int t> int gfield< T, t >::setKernelXbarX (int x_global, int y_global, positions * pos, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in position space, the x component.
Takes for arguments the global position and the positions object to avoid recomputation of sin functions, and the KernelChoice. Sets the values of the global gfield and has to be rerun for each x_global, y_global position. The values are summed to calculate the corresponding JIMWLK kernel. In the optimized version this is included in the prepare_A_and_B function.
Definition at line 1262 of file field.h.
References LINEAR_KERNEL, Nx, gfield< T, t >::Nxg, Ny, gfield< T, t >::Nyg, SIN_KERNEL, field< T, t >::u, positions::xbar2(), positions::xhatX(), and positions::xhatY().
Referenced by main().
setKernelXbarXWithCouplingConstant()
template<class T , int t> int gfield< T, t >::setKernelXbarXWithCouplingConstant (int x_global, int y_global, positions * pos, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in position space, the x component.
Takes for arguments the global position and the positions object to avoid recomputation of sin functions, and the KernelChoice. Sets the values of the global gfield and has to be rerun for each x_global, y_global position. The values are summed to calculate the corresponding JIMWLK kernel. Includes the effects of the running coupling. In the optimized version this is included in the prepare_A_and_B function.
Definition at line 1403 of file field.h.
References LINEAR_KERNEL, Nx, gfield< T, t >::Nxg, Ny, gfield< T, t >::Nyg, SIN_KERNEL, field< T, t >::u, positions::xbar2(), positions::xhatX(), and positions::xhatY().
Referenced by main().
setKernelXbarY()
template<class T , int t> int gfield< T, t >::setKernelXbarY (int x_global, int y_global, positions * pos, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in position space, the y component.
Takes for arguments the global position and the positions object to avoid recomputation of sin functions, and the KernelChoice. Sets the values of the global gfield and has to be rerun for each x_global, y_global position. The values are summed to calculate the corresponding JIMWLK kernel. In the optimized version this is included in the prepare_A_and_B function.
Definition at line 1332 of file field.h.
References LINEAR_KERNEL, Nx, gfield< T, t >::Nxg, Ny, gfield< T, t >::Nyg, SIN_KERNEL, field< T, t >::u, positions::xbar2(), positions::xhatX(), and positions::xhatY().
Referenced by main().
setKernelXbarYWithCouplingConstant()
template<class T , int t> int gfield< T, t >::setKernelXbarYWithCouplingConstant (int x_global, int y_global, positions * pos, Kernel KernelChoice)
Function to set the value of the JIMWLK kernel in position space, the x component.
Takes for arguments the global position and the positions object to avoid recomputation of sin functions, and the KernelChoice. Sets the values of the global gfield and has to be rerun for each x_global, y_global position. The values are summed to calculate the corresponding JIMWLK kernel. Includes the effects of the running coupling. In the optimized version this is included in the prepare_A_and_B function.
Definition at line 1482 of file field.h.
References LINEAR_KERNEL, Nx, gfield< T, t >::Nxg, Ny, gfield< T, t >::Nyg, SIN_KERNEL, field< T, t >::u, positions::xbar2(), positions::xhatX(), and positions::xhatY().
Referenced by main().
setToZero()
template<class T, int t> int gfield< T, t >::setToZero (void) inline
Definition at line 173 of file field.h.
References field< T, t >::u.
Referenced by main(), operator*(), and operator+().
Friends And Related Function Documentation
fftw2D
template<class T, int t> friend class fftw2D friend
Definition at line 145 of file field.h.
Referenced by main().
Member Data Documentation
Nxg
template<class T, int t> int gfield< T, t >::Nxg private
Specialization of the field class to a GLOBAL object.
Parameters
sizes of the global lattice
Exceptions
exception in case of errors.
Definition at line 135 of file field.h.
Referenced by gfield< T, t >::allgather(), gfield< T, t >::multiplyByCholesky(), gfield< T, t >::printDebug(), gfield< T, t >::setKernelXbarX(), gfield< T, t >::setKernelXbarXWithCouplingConstant(), gfield< T, t >::setKernelXbarY(), and gfield< T, t >::setKernelXbarYWithCouplingConstant().
Nyg [1/2]
template<class T, int t> int gfield< T, t >::Nyg private
Definition at line 135 of file field.h.
Referenced by gfield< T, t >::allgather(), gfield< T, t >::multiplyByCholesky(), gfield< T, t >::printDebug(), gfield< T, t >::setKernelXbarX(), gfield< T, t >::setKernelXbarXWithCouplingConstant(), gfield< T, t >::setKernelXbarY(), and gfield< T, t >::setKernelXbarYWithCouplingConstant().
Nyg [2/2]
template<class T, int t> gfield< T, t >::Nyg = NNy
Definition at line 141 of file field.h.
The documentation for this class was generated from the following file:
field.h