numJIMWLK++: mpi_class Class Reference
mpi_class Class Reference
#include <mpi_class.h>
Public Member Functions
mpi_class (int argc, char *argv[])
mpi_class ()
int mpi_init (config *cnfg)
int mpi_exchange_grid ()
int mpi_exchange_groups ()
int getRank ()
int getSize ()
MPI_Comm getRowComm ()
MPI_Comm getColComm ()
int getExchangeX ()
int getExchangeY ()
int getXNeighbourNext ()
int getYNeighbourNext ()
int getXNeighbourPrevious ()
int getYNeighbourPrevious ()
int getPosX ()
int getPosY ()
Private Attributes
int size
int rank
int proc_grid [2]
MPI_Comm row_comm
MPI_Comm col_comm
int XNeighbourNext
int XNeighbourPrevious
int YNeighbourNext
int YNeighbourPrevious
int ExchangeX
int ExchangeY
int pos_x
int pos_y
int n_pos_x
int n_pos_y
int p_pos_x
int p_pos_y
Detailed Description
Definition at line 38 of file mpi_class.h.
Constructor & Destructor Documentation
mpi_class() [1/2]
mpi_class::mpi_class (int argc, char * argv[]) inline
Definition at line 63 of file mpi_class.h.
mpi_class() [2/2]
mpi_class::mpi_class () inline
Definition at line 87 of file mpi_class.h.
References mpi_exchange_grid(), mpi_exchange_groups(), and mpi_init().
Member Function Documentation
getColComm()
MPI_Comm mpi_class::getColComm () inline
Definition at line 116 of file mpi_class.h.
References col_comm.
Referenced by main().
getExchangeX()
int mpi_class::getExchangeX () inline
Definition at line 121 of file mpi_class.h.
References ExchangeX.
Referenced by lfield< T, t >::mpi_exchange_boundaries().
getExchangeY()
int mpi_class::getExchangeY () inline
Definition at line 127 of file mpi_class.h.
References ExchangeY.
getPosX()
int mpi_class::getPosX () inline
Definition at line 157 of file mpi_class.h.
References pos_x.
Referenced by main(), momenta::momenta(), positions::positions(), prepare_A_local(), lfield< T, t >::print(), print(), lfield< T, t >::printDebug(), gfield< T, t >::reduce(), gfield< T, t >::reduce_hatta(), lfield< T, t >::setKernelPbarX(), lfield< T, t >::setKernelPbarXWithCouplingConstant(), lfield< T, t >::setKernelPbarY(), and lfield< T, t >::setKernelPbarYWithCouplingConstant().
getPosY()
int mpi_class::getPosY () inline
Definition at line 162 of file mpi_class.h.
References pos_y.
Referenced by main(), momenta::momenta(), positions::positions(), prepare_A_local(), lfield< T, t >::print(), print(), lfield< T, t >::printDebug(), gfield< T, t >::reduce(), gfield< T, t >::reduce_hatta(), lfield< T, t >::setKernelPbarX(), lfield< T, t >::setKernelPbarXWithCouplingConstant(), lfield< T, t >::setKernelPbarY(), and lfield< T, t >::setKernelPbarYWithCouplingConstant().
getRank()
int mpi_class::getRank () inline
Definition at line 99 of file mpi_class.h.
References rank.
Referenced by lfield< T, t >::mpi_exchange_boundaries(), lfield< T, t >::print(), print(), and rand_class::rand_class().
getRowComm()
MPI_Comm mpi_class::getRowComm () inline
Definition at line 111 of file mpi_class.h.
References row_comm.
Referenced by main().
getSize()
int mpi_class::getSize () inline
Definition at line 104 of file mpi_class.h.
References size.
Referenced by gfield< T, t >::allgather(), lfield< T, t >::print(), and print().
getXNeighbourNext()
int mpi_class::getXNeighbourNext () inline
Definition at line 133 of file mpi_class.h.
References XNeighbourNext.
Referenced by lfield< T, t >::mpi_exchange_boundaries().
getXNeighbourPrevious()
int mpi_class::getXNeighbourPrevious () inline
Definition at line 145 of file mpi_class.h.
References XNeighbourPrevious.
Referenced by lfield< T, t >::mpi_exchange_boundaries().
getYNeighbourNext()
int mpi_class::getYNeighbourNext () inline
Definition at line 139 of file mpi_class.h.
References YNeighbourNext.
getYNeighbourPrevious()
int mpi_class::getYNeighbourPrevious () inline
Definition at line 151 of file mpi_class.h.
References YNeighbourPrevious.
mpi_exchange_grid()
int mpi_class::mpi_exchange_grid (void)
Definition at line 36 of file mpi_exchange_grid.cpp.
References ExchangeX, ExchangeY, n_pos_x, n_pos_y, p_pos_x, p_pos_y, pos_x, pos_y, proc_grid, rank, XNeighbourNext, XNeighbourPrevious, YNeighbourNext, and YNeighbourPrevious.
Referenced by main(), and mpi_class().
mpi_exchange_groups()
int mpi_class::mpi_exchange_groups (void)
Definition at line 37 of file mpi_exchange_groups.cpp.
References col_comm, proc_grid, rank, row_comm, and size.
Referenced by main(), and mpi_class().
mpi_init()
int mpi_class::mpi_init (config * cnfg)
Definition at line 36 of file mpi_init.cpp.
References ExchangeX, ExchangeY, Nx, config::Nxl, config::Nxl_buf, Ny, config::Nyl, config::Nyl_buf, pos_x, pos_y, proc_grid, rank, and size.
Referenced by main(), and mpi_class().
Member Data Documentation
col_comm
MPI_Comm mpi_class::col_comm private
Definition at line 47 of file mpi_class.h.
Referenced by getColComm(), and mpi_exchange_groups().
ExchangeX
int mpi_class::ExchangeX private
Definition at line 52 of file mpi_class.h.
Referenced by getExchangeX(), mpi_exchange_grid(), and mpi_init().
ExchangeY
int mpi_class::ExchangeY private
Definition at line 52 of file mpi_class.h.
Referenced by getExchangeY(), mpi_exchange_grid(), and mpi_init().
n_pos_x
int mpi_class::n_pos_x private
Definition at line 58 of file mpi_class.h.
Referenced by mpi_exchange_grid().
n_pos_y
int mpi_class::n_pos_y private
Definition at line 58 of file mpi_class.h.
Referenced by mpi_exchange_grid().
p_pos_x
int mpi_class::p_pos_x private
Definition at line 59 of file mpi_class.h.
Referenced by mpi_exchange_grid().
p_pos_y
int mpi_class::p_pos_y private
Definition at line 59 of file mpi_class.h.
Referenced by mpi_exchange_grid().
pos_x
int mpi_class::pos_x private
Definition at line 55 of file mpi_class.h.
Referenced by getPosX(), mpi_exchange_grid(), and mpi_init().
pos_y
int mpi_class::pos_y private
Definition at line 56 of file mpi_class.h.
Referenced by getPosY(), mpi_exchange_grid(), and mpi_init().
proc_grid
int mpi_class::proc_grid[2] private
Definition at line 44 of file mpi_class.h.
Referenced by mpi_exchange_grid(), mpi_exchange_groups(), and mpi_init().
rank
int mpi_class::rank private
Definition at line 42 of file mpi_class.h.
Referenced by getRank(), mpi_exchange_grid(), mpi_exchange_groups(), and mpi_init().
row_comm
MPI_Comm mpi_class::row_comm private
Definition at line 46 of file mpi_class.h.
Referenced by getRowComm(), and mpi_exchange_groups().
size
int mpi_class::size private
Definition at line 42 of file mpi_class.h.
Referenced by getSize(), mpi_exchange_groups(), and mpi_init().
XNeighbourNext
int mpi_class::XNeighbourNext private
Definition at line 49 of file mpi_class.h.
Referenced by getXNeighbourNext(), and mpi_exchange_grid().
XNeighbourPrevious
int mpi_class::XNeighbourPrevious private
Definition at line 49 of file mpi_class.h.
Referenced by getXNeighbourPrevious(), and mpi_exchange_grid().
YNeighbourNext
int mpi_class::YNeighbourNext private
Definition at line 50 of file mpi_class.h.
Referenced by getYNeighbourNext(), and mpi_exchange_grid().
YNeighbourPrevious
int mpi_class::YNeighbourPrevious private
Definition at line 50 of file mpi_class.h.
Referenced by getYNeighbourPrevious(), and mpi_exchange_grid().
The documentation for this class was generated from the following files:
mpi_class.h
mpi_exchange_grid.cpp
mpi_exchange_groups.cpp
mpi_init.cpp