numJIMWLK++: field.h File Reference
field.h File Reference
#include <iostream>
#include <stdlib.h>
#include <complex>
#include <ccomplex>
#include "config.h"
#include <omp.h>
#include <mpi.h>
#include <math.h>
#include "mpi_class.h"
#include "MV_class.h"
#include "rand_class.h"
#include "momenta.h"
#include "positions.h"
#include <random>
#include <time.h>
#include <thread>
Classes
class field< T, t >
Definition of the main class of type field.
class lfield< T, t >
class gmatrix< T >
class gfield< T, t >
Derived class gfield.
class lfield< T, t >
Functions
template<class T , int t>
lfield< T, t > operator* (const lfield< T, t > &f, const lfield< T, t > &g)
template<class T , int t>
gfield< T, t > operator* (const gfield< T, t > &f, const gfield< T, t > &g)
template<class T , int t>
lfield< T, t > operator+ (const lfield< T, t > &f, const lfield< T, t > &g)
template<class T , int t>
gfield< T, t > operator+ (const gfield< T, t > &f, const gfield< T, t > &g)
template<class T , int t>
int print (lfield< T, t > *sum, lfield< T, t > *err, momenta *mom, double x, mpi_class *mpi)
Simple print function.
template<class T , int t>
int uxiulocal (lfield< T, t > *uxiulocal_x, lfield< T, t > *uxiulocal_y, lfield< T, t > *uf, lfield< T, t > *xi_local_x, lfield< T, t > *xi_local_y)
Optimized method to compute the product of Wilson line U, noise vector xi and hermitian conjugate of the Wilson line.
template<class T , int t>
int update_uf (lfield< T, t > *uf, lfield< T, t > *B_local, lfield< T, t > *A_local, double step)
Main method for the advance of the Wilson lines in rapidity according to the Langevin equation.
template<class T , int t>
int prepare_A_local (lfield< T, t > *A_local, lfield< T, t > *xi_local_x, lfield< T, t > *xi_local_y, momenta *mom, mpi_class *mpi, Coupling p, Kernel kk)
Optimized method for the evaluation of the A and B matrices.
template<class T , int t>
int prepare_A_local (lfield< T, t > *A_local, lfield< T, t > *xi_local_x, lfield< T, t > *xi_local_y, lfield< T, t > *kernel_pbarx, lfield< T, t > *kernel_pbary)
Unoptimized method for the evaluation of the A and B matrices.
template<class T , int t>
int generate_gaussian (lfield< T, t > *xi_local_x, lfield< T, t > *xi_local_y, mpi_class *mpi, config *cnfg)
Method for generation of the noise vectors with a gaussian distribution in the Lie algebra.
template<class T , int t>
int generate_gaussian_with_noise_coupling_constant (lfield< T, t > *xi_local_x, lfield< T, t > *xi_local_y, momenta *mom, mpi_class *mpi, config *cnfg)
Method for generation of the noise vectors with a gaussian distribution rescaled by the coupling constant in the Lie algebra.
template<class T , int t>
int prepare_A_and_B_local (int x, int y, int x_global, int y_global, gfield< T, t > *xi_global_x, gfield< T, t > *xi_global_y, lfield< T, t > *A_local, lfield< T, t > *B_local, gfield< T, t > *uf_global, positions *postable, int rr, Coupling p, Kernel kk)
Optimized method for the evaluation of the A and B matrices.
template<class T , int t>
int print (int measurement, lfield< T, t > *sum, lfield< T, t > *err, momenta *mom, double x, mpi_class *mpi, std::string const &fileroot)
Main output function.
Function Documentation
generate_gaussian()
template<class T , int t> int generate_gaussian (lfield< T, t > * xi_local_x, lfield< T, t > * xi_local_y, mpi_class * mpi, config * cnfg)
Method for generation of the noise vectors with a gaussian distribution in the Lie algebra.
Implementation of Eqs. 24 ad 25 of arxiv XXXXXX
Definition at line 2333 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), and field< T, t >::u.
Referenced by main().
generate_gaussian_with_noise_coupling_constant()
template<class T , int t> int generate_gaussian_with_noise_coupling_constant (lfield< T, t > * xi_local_x, lfield< T, t > * xi_local_y, momenta * mom, mpi_class * mpi, config * cnfg)
Method for generation of the noise vectors with a gaussian distribution rescaled by the coupling constant in the Lie algebra.
Implementation of Eq. 47 of arxiv XXXXXX
Definition at line 2427 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), Nx, Ny, momenta::phat2(), and field< T, t >::u.
Referenced by main().
operator*() [1/2]
template<class T , int t> lfield<T,t> operator* (const lfield< T, t > & f, const lfield< T, t > & g)
Definition at line 439 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), su3_matrix< T >::m, lfield< T, t >::setToZero(), and field< T, t >::u.
operator*() [2/2]
template<class T , int t> gfield<T,t> operator* (const gfield< T, t > & f, const gfield< T, t > & g)
Definition at line 476 of file field.h.
References gfield< T, t >::getNxg(), gfield< T, t >::getNyg(), su3_matrix< T >::m, gfield< T, t >::setToZero(), and field< T, t >::u.
operator+() [1/2]
template<class T , int t> lfield<T,t> operator+ (const lfield< T, t > & f, const lfield< T, t > & g)
Definition at line 515 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), su3_matrix< T >::m, lfield< T, t >::setToZero(), and field< T, t >::u.
operator+() [2/2]
template<class T , int t> gfield<T,t> operator+ (const gfield< T, t > & f, const gfield< T, t > & g)
Definition at line 552 of file field.h.
References gfield< T, t >::getNxg(), gfield< T, t >::getNyg(), su3_matrix< T >::m, gfield< T, t >::setToZero(), and field< T, t >::u.
prepare_A_and_B_local()
template<class T , int t> int prepare_A_and_B_local (int x, int y, int x_global, int y_global, gfield< T, t > * xi_global_x, gfield< T, t > * xi_global_y, lfield< T, t > * A_local, lfield< T, t > * B_local, gfield< T, t > * uf_global, positions * postable, int rr, Coupling p, Kernel kk)
Optimized method for the evaluation of the A and B matrices.
Operates on the seven and eight arguments, takes the xi_x, xi_y, positions and the actual Wilson line field uf_global. Construction of the JIMWLK kernel is performed here due to optimization reasons. Used in the position space construction. Implementation of Eqs. 34 ad 38 of arxiv XXXXXX in position space, without Fourier transforms
Definition at line 2527 of file field.h.
References lfield< T, t >::getNyl(), HATTA_COUPLING_CONSTANT, LINEAR_KERNEL, su3_matrix< T >::m, NO_COUPLING_CONSTANT, NOISE_COUPLING_CONSTANT, Nx, Ny, SIN_KERNEL, SQRT_COUPLING_CONSTANT, field< T, t >::u, positions::xbar2(), positions::xhatX(), and positions::xhatY().
Referenced by main().
prepare_A_local() [1/2]
template<class T , int t> int prepare_A_local (lfield< T, t > * A_local, lfield< T, t > * xi_local_x, lfield< T, t > * xi_local_y, momenta * mom, mpi_class * mpi, Coupling p, Kernel kk)
Optimized method for the evaluation of the A and B matrices.
Operates on the first argument, takes the xi_x, xi_y and momenta. Construction of the JIMWLK kernel is performed here due to optimization reasons. Implementation of Eqs. 35 ad 38 of arxiv XXXXXX
Definition at line 2207 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), mpi_class::getPosX(), mpi_class::getPosY(), LINEAR_KERNEL, su3_matrix< T >::m, NO_COUPLING_CONSTANT, NOISE_COUPLING_CONSTANT, Nx, Ny, momenta::pbarX(), momenta::pbarY(), momenta::phat2(), SIN_KERNEL, SQRT_COUPLING_CONSTANT, and field< T, t >::u.
Referenced by main().
prepare_A_local() [2/2]
template<class T , int t> int prepare_A_local (lfield< T, t > * A_local, lfield< T, t > * xi_local_x, lfield< T, t > * xi_local_y, lfield< T, t > * kernel_pbarx, lfield< T, t > * kernel_pbary)
Unoptimized method for the evaluation of the A and B matrices.
Operates on the first argument, takes the xi_x, xi_y and the precomputed kernel objects. Implementation of Eqs. 35 ad 38 of arxiv XXXXXX
xi_local_x_tmp = kernel_pbarx * xi_local_x; xi_local_y_tmp = kernel_pbary * xi_local_y;
A_local = xi_local_x_tmp + xi_local_y_tmp;
Definition at line 2295 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), su3_matrix< T >::m, and field< T, t >::u.
print() [1/2]
template<class T , int t> int print (lfield< T, t > * sum, lfield< T, t > * err, momenta * mom, double x, mpi_class * mpi)
Simple print function.
Not used in the optimized version.
Definition at line 1946 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), mpi_class::getPosX(), mpi_class::getPosY(), mpi_class::getRank(), mpi_class::getSize(), momenta::phat2(), and field< T, t >::u.
Referenced by main(), and lfield< T, t >::setToFixed().
print() [2/2]
template<class T , int t> int print (int measurement, lfield< T, t > * sum, lfield< T, t > * err, momenta * mom, double x, mpi_class * mpi, std::string const & fileroot)
Main output function.
Each MPI node prints its part of the correlation function to a file of provided name. Function prints the rapidity step, the correlation and its standard deviation. Additional arguments are needed: momenta* to print the k_T. The statistics is passed through x argument.
Definition at line 2676 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), mpi_class::getPosX(), mpi_class::getPosY(), mpi_class::getRank(), mpi_class::getSize(), Nx, Ny, momenta::phat2(), and field< T, t >::u.
update_uf()
template<class T , int t> int update_uf (lfield< T, t > * uf, lfield< T, t > * B_local, lfield< T, t > * A_local, double step)
Main method for the advance of the Wilson lines in rapidity according to the Langevin equation.
Operates on the first argument, takes the A and B matrices and the Langevin discretization step. Implementation of Eq. 22 of arxiv XXXXXX
A_local.exponentiate(sqrt(step));
B_local.exponentiate(-sqrt(step));
uf = B_local * uf * A_local;
Definition at line 2172 of file field.h.
References su3_matrix< T >::exponentiate(), lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), su3_matrix< T >::m, and field< T, t >::u.
Referenced by main().
uxiulocal()
template<class T , int t> int uxiulocal (lfield< T, t > * uxiulocal_x, lfield< T, t > * uxiulocal_y, lfield< T, t > * uf, lfield< T, t > * xi_local_x, lfield< T, t > * xi_local_y)
Optimized method to compute the product of Wilson line U, noise vector xi and hermitian conjugate of the Wilson line.
uf_hermitian = uf.hermitian();
uxiulocal_x = uf * xi_local_x * (*uf_hermitian); uxiulocal_y = uf * xi_local_y * (*uf_hermitian);
delete uf_hermitian;
(1.0*Nx*Ny);
(1.0*Nx*Ny);
Definition at line 2126 of file field.h.
References lfield< T, t >::getNxl(), lfield< T, t >::getNyl(), su3_matrix< T >::m, and field< T, t >::u.
Referenced by main().