numJIMWLK++: main_omp.cpp File Reference
main_omp.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>
#include <complex.h>
#include "su3_matrix.h"
#include "config.h"
#include <fftw3.h>
#include <fftw3-mpi.h>
#include "field.h"
#include "matrix.h"
#include "mpi_fftw_class.h"
#include <omp.h>
#include <math.h>
#include "mpi_class.h"
#include "momenta.h"
#include "rand_class.h"
#include "MV_class.h"
#include <numeric>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 35 of file main_omp.cpp.
References gfield< T, t >::allgather(), gmatrix< T >::decompose(), lfield< T, t >::exponentiate(), MV_class::g_parameter, mpi_class::getColComm(), mpi_class::getPosX(), mpi_class::getPosY(), mpi_class::getRowComm(), gfield< T, t >::hermitian(), lfield< T, t >::hermitian(), mpi_class::mpi_exchange_grid(), mpi_class::mpi_exchange_groups(), mpi_class::mpi_init(), MV_class::mu_parameter, gfield< T, t >::multiplyByCholesky(), Nx, config::Nxl, Ny, MV_class::Ny_parameter, config::Nyl, lfield< T, t >::reduceAndSet(), momenta::set(), lfield< T, t >::setCorrelationsForCouplingConstant(), lfield< T, t >::setGaussian(), lfield< T, t >::setKernelPbarX(), lfield< T, t >::setKernelPbarXWithCouplingConstant(), lfield< T, t >::setKernelPbarY(), lfield< T, t >::setKernelPbarYWithCouplingConstant(), gfield< T, t >::setKernelXbarX(), gfield< T, t >::setKernelXbarXWithCouplingConstant(), gfield< T, t >::setKernelXbarY(), gfield< T, t >::setKernelXbarYWithCouplingConstant(), lfield< T, t >::setMVModel(), lfield< T, t >::solvePoisson(), config::stat, and lfield< T, t >::trace().