numJIMWLK++: tests/test_accumulation.cpp File Reference
test_accumulation.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <mpi.h>
#include <complex.h>
#include "../su3_matrix.h"
#include "../config.h"
#include <fftw3.h>
#include <fftw3-mpi.h>
#include "../field.h"
#include "../mpi_fftw_class.h"
#include <omp.h>
#include <math.h>
#include "../mpi_class.h"
#include "../momenta.h"
#include "../rand_class.h"
#include "../MV_class.h"
#include <numeric>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 34 of file test_accumulation.cpp.
References fftw2D::init2D(), mpi_class::mpi_exchange_grid(), mpi_class::mpi_init(), Nx, config::Nxl, Ny, MV_class::NyGet(), config::Nyl, momenta::set(), lfield< T, t >::setToOne(), lfield< T, t >::setToZero(), config::stat, and lfield< T, t >::trace().